# Generated by Django 2.2.4 on 2021-03-20 00:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20210318_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='snippet',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
